management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - mappings
          - metrics
          - env

spring:
  datasource:
    url: jdbc:postgresql://35.188.185.141:5432/cert
    username: postgres
    password: password
    platform: POSTGRESQL